[package]
name = "factorio-blueprint-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
factorio-blueprint = { path = "../factorio-blueprint" }
clap = "3.0.10"
